### PR TITLE
scopedef: Fix minor docstring formatting bug

### LINKED ISSUE #117: doc: Some bad renderings of Sphinx markup?
From here (as of a2ae7a7):
https://pygccxml.readthedocs.io/en/develop/apidocs/pygccxml.declarations.scopedef.html?highlight=recursive_default#pygccxml.declarations.scopedef.scopedef_t

I see this:
> image

Seems like some minor line alignment stuff?

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Resolves #117

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
Before:
> image
After:
> image

**Comment by EricCousineau-TRI** [comment]
Huh... dunno why that alignment looks so crappy...

**Comment by EricCousineau-TRI** [comment]
Here's what f33199b does:
> image

**Comment by iMichka** [comment]
Thanks for the cleanup @EricCousineau-TRI

**Pull request merged**
