### PR TITLE
unittests.test_all: Add option to run in parallel

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Report isn't great, but it runs faster?

Was running unittests, but it was a bit slow to run them serially...
Here's one option, but it is admittedly a tad messy.

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
Better solution may be a 3rd party lib, if it's an OK cost in terms of build-dependencies:
https://stackoverflow.com/q/4710142/7829525

**Comment by iMichka** [comment]
Hi. Thanks for the pull request. I know that the tests are slow, but at least we have them :)

What I would like is:
- Replace some tests by real unit tests. Most tests here are just integration tests, and running castxml on the different tests files is what makes the tests slow. This would be a long term goal and I do not have much time to work on this.
- Use pytest, which can also be run in parallel if I remember well.

 My plan is to tag release 2.0 as soon as possible. I am not really working a lot on pygccxml lately, so I am not up for bigger changes in the infrastructure right now, unless absolutely necessary.

**Comment by iMichka** [comment]
To be clear: I would not like to add so much code to run the tests in parallel right now. I'll close this, and we can keep in mind that there are some long term ideas above on how to improve the situation.

**Comment by EricCousineau-TRI** [comment]
Makes sense - thanks for writing that out!

**Pull request closed without merging**
